defaultPlacement: end
fieldLayouts:
  8080620b-f1db-4c82-b57e-21876c8bdbf4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: b0e8ab5d-d1b4-41ba-a854-492fef3cd7fc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 20e63555-9b42-4378-852f-b04efedfa306
            userCondition: null
            warning: null
          -
            attribute: newWindow
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: 0d931000-0adb-4b38-8fdd-2fc1a3271f89
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: f9022887-f05b-4b3b-9950-4f45e2b72026
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 3ed35f71-7361-4e45-9172-b4e5ca2641de
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: fbcfb3e8-0fae-41c6-af7f-07e217ff3894
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: de1c0879-817c-414c-8125-ad6b2a7bd6a2
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 858d09f7-19d8-40cd-8eba-81e99e6668fb
        userCondition: null
handle: mainMenu
instructions: ''
maxNodes: null
name: Menu
permissions:
  craft\elements\Asset:
    enabled: ''
    permissions: '*'
  craft\elements\Category:
    enabled: ''
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions:
      - 'section:86f4b979-439d-4d67-8e6d-053a5ddf4c89' # Pages
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: ''
propagationMethod: all
siteSettings:
  b770f7e5-3411-4c52-91e3-c5929d334207: # CraftDev
    enabled: true
sortOrder: 1
structure:
  maxLevels: null
  uid: 28990cae-62e3-48a8-9518-c84aba9efba7
