defaultPlacement: end
enableVersioning: true
entryTypes:
  - ecdde3a3-5dd0-4fd9-9c08-03b0a6dc6076 # Demo
  - c4cf33a7-639f-48ca-a3bb-41a1e43c323b # CTA
  - 0d8e3a10-fa18-468b-891d-7a206f55bfed # Articles
  - a92b0c28-f216-432b-9f5e-d8359af61da6 # Bilder
  - 9659d51a-1688-4cf0-9c10-8c6800c80b1b # Longform Content
handle: demosection
maxAuthors: 1
name: 'Demo Section'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre Eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b770f7e5-3411-4c52-91e3-c5929d334207: # CraftDev
    enabledByDefault: true
    hasUrls: true
    template: demosection/_entry
    uriFormat: 'demosection/{slug}'
structure:
  maxLevels: null
  uid: 5db9b75f-4a32-4e06-bda1-66fa2d3e9cf4
type: structure
