columnSuffix: null
handle: longformContent
instructions: null
name: 'Longform Inhalt'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 3d18b3d4-9460-4d18-a77f-13a9247fd075 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
