color: red
fieldLayouts:
  742dae6f-457a-4d6d-81f0-5f875418b9b7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 477935ab-ca7f-482e-a56a-5508babc2fc9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aa912073-977f-4f2e-9694-d416e9e592cf # Demo Data
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fde756c-2aea-4fbb-9eb5-9aef37b8dcd3
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: d8d4580e-763c-4ad6-91f7-8a737a9fe15f
        userCondition: null
handle: articles
hasTitleField: true
icon: newspaper
name: Articles
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
