color: null
fieldLayouts:
  c7961e08-149b-4841-beef-9fc1548dfa18:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 086d31f3-ce4c-4b47-8222-4da023307f44
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 997efcbf-e489-4605-b17d-df922007f924
        userCondition: null
handle: blogOverview
hasTitleField: true
icon: ''
name: Blog-Overview
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
