color: null
fieldLayouts:
  16ce9aaa-656d-4539-9c9e-97e9242e4bf9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a3aee760-91af-443c-a992-2af55fd97f3f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e57dd80e-fbbb-45c8-9086-b5a5368c2429 # Image Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec857fce-7a21-4e98-8f41-4aa89d0b144a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 62546cb3-3b56-4a0b-a2ff-a03206f9462f
        userCondition: null
handle: home
hasTitleField: true
icon: ''
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
